repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=1100']

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        args: ["--line-length", "120"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        # Only run flake8 on specific critical checks initially
        args: ["--select=E9,F63,F7,F82", "--show-source"]

# Commenting out bandit for initial setup until code quality improves
# -   repo: https://github.com/PyCQA/bandit
#     rev: 1.7.5
#     hooks:
#     -   id: bandit
#         args: ["-r", "src"]
#         exclude: tests/
